### ISSUE TITLE
Cannot get button_remapping to work with AppleTV

### ISSUE THREAD

**Issue by bakernigel** [dezihh/my-harmony-card#27]
I've been pulling my hair out trying to get the OK button to work with my AppleTV. 
Looking at the instructions it seems I need to do button_remapping to map the OK button to Select. 
Here is my configuration based on your simple example:
```
name: Remote
entity: remote.harmony_hub
activities:
  Watch AppleTV:
    button_remapping:
      OK: Select
    device_id: 79834149
    volume_device_id: 79843969
    Button1:
      icon: mdi:gesture-two-double-tap
      command: Settings
      tooltip: Settings for my AppleTV
```
I turned on debug mode and see command OK is still being sent:
```
my-harmony-card.js?hacstag=8129167961410:1344 _button Pressed - DeviceId: 79834149 - Command: OK - entity_id: remote.harmony_hub
```
This is what is in the harmonyxxx.conf file for the Apple TV.
```
        "Apple TV Gen 2/3": {
            "commands": [
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Select",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "SkipBack",
                "SkipForward",
                "Menu",
                "Back",
                "Home",
                "NextChapter",
                "Pair",
                "PrevChapter",
                "Reboot",
                "UnPair",
                "VideoMode"
            ],
            "id": "79834149"
```
Not sure what I am doing wrong. Any help would be much appreciated. This is by far the best implementation of the Harmony remote on Home Assistant.

**Comment by dezihh** [comment]
Good morning and thank you! :-)

I assume in you config is one part too much: `button_remapping:`
Please try it like this:
```
name: Remote
entity: remote.harmony_hub
activities:
  Watch AppleTV:
    device_id: 79834149  
    OK: Select
    volume_device_id: 79843969
    Button1:
      icon: mdi:gesture-two-double-tap
      command: Settings
      tooltip: Settings for my AppleTV
```
